In [9]:
# Mise à jour de issuesFermetures.csv'
import pandas as pd

issues=pd.read_csv('https://raw.githubusercontent.com/ExploitIdF/IssuesTunnels/main/_static/issuesTunnelsDIRIF.csv')
CorTbFerm=pd.read_csv('https://raw.githubusercontent.com/ExploitIdF/ReferentielTunnels/refs/heads/main/CorTbFerm.csv')
issuesFermetures=issues[['CodeEx', 'PC', 'Tatouage', 'triCode' ,'Sens']] .join(CorTbFerm.set_index(['triCode','Sens'])['Fermeture'],on=['triCode','Sens'])
tunTriC=pd.read_csv('CorTbFerm.csv')[['triCode','Tunnel']].drop_duplicates().set_index('Tunnel')

                   triCode
Tunnel
LA_DEFENSE             A14
NEUILLY                NEU
ECHANGEUR_NANTERRE     ECH
SAINT-CLOUD            SCL
AMBROISE_PARE          BAP
BICETRE                BIC
ITALIE                 ITA
LA_COURNEUVE           CRN
BOBIGNY                BDR
LUMEN_NORTON           LNO
BOISSY                 BOI
CHAMPIGNY              CHA
CHENNEVIERES           CHE
FONTENAY               FLF
FRESNES                FRE
ANTONY                 ANT
GUY-MOQUET             GMO
MOULIN                 MOU
LANDY                  LAN
NANTERRE_CENTRE        NAN
NOGENT                 NOG
ORLY                   ORL
BELLE-RIVE             RUE
SEVINES                SEV
TAVERNY                TAV

In [3]:
if True :
    issuesFermetures.to_csv('issuesFermetures.csv',index=False)

In [10]:
niches=pd.read_csv('https://raw.githubusercontent.com/ExploitIdF/IssuesTunnels/main/_static/nichesBrExPc.csv').join(tunTriC,on='Tunnel')

In [11]:
niches[:1]

,Entité,Tatouage,CodeEx,Axe,Sens,Description,Tunnel,GPS,type,nbrBr,nbrEx,nbrPc,triCode
0,AGER_OUEST_N,L10.122A,DEF-NSW-701/DEF,N1013,W,Niche sécurité NSW-701 - PAU NM01R - Tunnel de...,LA_DEFENSE,"48.889957,2.239356",sécurité,1,2,1,A14

In [14]:
nichesFermetures=niches[['CodeEx',  'Tatouage', 'triCode' ,'Sens']] .join(CorTbFerm.set_index(['triCode','Sens'])['Fermeture'],on=['triCode','Sens'])
nichesFermetures.to_csv('nichesFermetures.csv',index=False)

In [13]:
niches

,Entité,Tatouage,CodeEx,Axe,Sens,Description,Tunnel,GPS,type,nbrBr,nbrEx,nbrPc,triCode
0,AGER_OUEST_N,L10.122A,DEF-NSW-701/DEF,N1013,W,Niche sécurité NSW-701 - PAU NM01R - Tunnel de...,LA_DEFENSE,"48.889957,2.239356",sécurité,1,2,1,A14
1,AGER_OUEST_N,L10.123C,DEF-NSW-702/DEF,N1013,W,Niche sécurité NSW-702 - PAU NM00R - Tunnel de...,LA_DEFENSE,"48.890278,2.240661",sécurité,1,2,1,A14
2,AGER_OUEST_N,L10.124D,DEF-NSW-601/DEF,N192,W,Niche sécurité NSW-601 - PAU NG01R - Tunnel de...,LA_DEFENSE,"48.892075,2.240956",sécurité,1,2,1,A14
3,AGER_OUEST_N,L10.125E,DEF-NSW-602/DEF,N192,W,Niche sécurité NSW-602 - PAU NG00S - Tunnel de...,LA_DEFENSE,"48.889793,2.243714",sécurité,1,2,1,A14
4,AGER_OUEST_N,L10.126F,DEF-NSW-603/DEF,N192,W,Niche sécurité NSW-603 - PAU NG00R - Tunnel de...,LA_DEFENSE,"48.890770,2.241594",sécurité,1,2,1,A14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,AGER_OUEST_B,L11.947W,NSEY/FON,A12,Y,Niche sécurité - Entré Y - PAU LR05A - Tunnel ...,FONTENAY,"48.807095,2.051986",sécurité,1,2,1,FLF
433,AGER_OUEST_B,L11.948X,NSSY/FON,A12,Y,Niche sécurité - Sortie Y - PAU LR05F - Tunnel...,FONTENAY,"48.803932,2.049182",sécurité,0,2,1,FLF
434,AGER_OUEST_B,L11.949Y,NSEW/FON,A12,W,Niche sécurité - Entré W - PAU LR05R - Tunnel ...,FONTENAY,"48.803936,2.049612",sécurité,1,2,1,FLF
435,AGER_OUEST_B,L11.951C,NSSW/FON,A12,W,Niche sécurité - Sortie W - PAU LR05W - Tunnel...,FONTENAY,"48.806843,2.052555",sécurité,0,2,1,FLF
436,AGER_OUEST_N,L11.959L,NAN-NSEE/DEF,A86OUEST,E,Niche sécurité NSEE/NAN - PAU RW80R - Tunnel d...,NANTERRE_CENTRE,"48.902800,2.204336",sécurité,0,0,0,NAN